Repository BootstrapBlazor/BootstrapBlazor.Extensions, pull requests merged in 2024-12, with the labels that each got.

#152 feat(Splitting): update static asset path
  src/components/BootstrapBlazor.Splitting/BootstrapBlazor.Splitting.csproj
  src/components/BootstrapBlazor.Splitting/Components/Splitting/Splitting.razor
  src/components/BootstrapBlazor.Splitting/Components/Splitting/Splitting.razor.css
  src/components/BootstrapBlazor.Splitting/Components/Splitting/Splitting.razor.js
  src/components/BootstrapBlazor.Splitting/wwwroot/splitting.bundle.css
Labels: enhancement

#155 feat(DockView): add ShowPin parameter
  src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
  src/components/BootstrapBlazor.DockView/Components/DockViewConfig.cs
  src/components/BootstrapBlazor.DockView/Components/DockViewV2.razor
  src/components/BootstrapBlazor.DockView/Components/DockViewV2.razor.cs
  src/components/BootstrapBlazor.DockView/wwwroot/css/dockview-bb.css
  src/components/BootstrapBlazor.DockView/wwwroot/icon/dockview.svg
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-config.js
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-core.esm.js
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-extensions.js
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-fix.js
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-group.js
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-icon.js
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-panel.js
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-utils.js
Labels: enhancement

#153 fix(Mermaid): support big data
  src/components/BootstrapBlazor.Mermaid/Mermaid.razor.js
Labels: enhancement

#158 feat(VideoPlayer): update javascript of dispose
  src/components/BootstrapBlazor.Mermaid/BootstrapBlazor.Mermaid.csproj
  src/components/BootstrapBlazor.VideoPlayer/BootstrapBlazor.VideoPlayer.csproj
  src/components/BootstrapBlazor.VideoPlayer/VideoPlayer.razor.js
Labels: enhancement

#160 feat(FontAwesome): upgrade font awesome to 6.7.1
  src/components/BootstrapBlazor.FontAwesome/BootstrapBlazor.FontAwesome.csproj
  src/components/BootstrapBlazor.FontAwesome/wwwroot/css/all.css
  src/components/BootstrapBlazor.FontAwesome/wwwroot/css/all.min.css
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-brands-400.ttf
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-brands-400.woff2
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-regular-400.ttf
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-regular-400.woff2
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-solid-900.ttf
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-solid-900.woff2
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-v4compatibility.ttf
  src/components/BootstrapBlazor.FontAwesome/wwwroot/webfonts/fa-v4compatibility.woff2
  src/components/BootstrapBlazor.VideoPlayer/BootstrapBlazor.VideoPlayer.csproj
Labels: enhancement

#163 chore(Config): update project toolchain
  .github/ISSUE_TEMPLATE/10_bug_report.yml
  .github/workflows/auto-pull-request-checks.yml
Labels: chore

#165 feat(Holiday): update 2025 workingday data
  src/components/BootstrapBlazor.Holiday/BootstrapBlazor.Holiday.csproj
  src/components/BootstrapBlazor.Holiday/Data/2025.json
Labels: enhancement

#166 feat(Editor): add GetCode method
  src/components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
  src/components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor
  src/components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.cs
  src/components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.js
Labels: enhancement

#168 feat(Editor): add async key word
  src/components/BootstrapBlazor.SummerNote/Components/Editor/Editor.razor.js
Labels: enhancement

#170 chore(Build): update action target to net9
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: chore

#172 feat(MeiliSearch): support composition input
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
Labels: enhancement

#174 refactor(Gantt): add bundle style
  src/components/BootstrapBlazor.Gantt/BootstrapBlazor.Gantt.csproj
  src/components/BootstrapBlazor.Gantt/Components/Gantt.razor
  src/components/BootstrapBlazor.Gantt/wwwroot/css/gantt.bundle.css
Labels: enhancement

#176 refactor(WinBox): use HeadContent render style link
  src/components/BootstrapBlazor.Gantt/Components/Gantt.razor
  src/components/BootstrapBlazor.WinBox/BootstrapBlazor.WinBox.csproj
  src/components/BootstrapBlazor.WinBox/WinBox.razor
  src/components/BootstrapBlazor.WinBox/WinBox.razor.js
Labels: enhancement

#177 refactor(MeiliSearch): use HeadContent render static assets
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
Labels: enhancement

#180 refactor(WinBox): revert use addLink process static assets
  src/components/BootstrapBlazor.WinBox/BootstrapBlazor.WinBox.csproj
  src/components/BootstrapBlazor.WinBox/WinBox.razor
  src/components/BootstrapBlazor.WinBox/WinBox.razor.js
Labels: enhancement

#182 refactor(SvgEditor): use HeadContent render static assets
  src/components/BootstrapBlazor.SVGEditor/BootstrapBlazor.SvgEditor.csproj
  src/components/BootstrapBlazor.SVGEditor/Components/SvgEditor/SvgEditor.razor
  src/components/BootstrapBlazor.SVGEditor/Components/SvgEditor/SvgEditor.razor.js
  src/components/BootstrapBlazor.SVGEditor/wwwroot/svgedit.bundle.css
Labels: enhancement

#184 fix(SvgEditor): update script path
  src/components/BootstrapBlazor.SVGEditor/BootstrapBlazor.SvgEditor.csproj
  src/components/BootstrapBlazor.SVGEditor/Components/SvgEditor/SvgEditor.razor
  src/components/BootstrapBlazor.SVGEditor/Components/SvgEditor/SvgEditor.razor.js
Labels: enhancement

#186 revert(MeiliSearch): remove HeadContent component
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
Labels: enhancement

#188 refactor(Gantt): update static assets link
  src/components/BootstrapBlazor.Gantt/BootstrapBlazor.Gantt.csproj
  src/components/BootstrapBlazor.Gantt/Components/Gantt.razor
  src/components/BootstrapBlazor.Gantt/Components/Gantt.razor.js
Labels: enhancement

#190 feat(MouseFollower): remove css isolation
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
  src/components/BootstrapBlazor.MouseFollower/BootstrapBlazor.MouseFollower.csproj
  src/components/BootstrapBlazor.MouseFollower/Components/MouseFollower/MouseFollower.razor.js
  src/components/BootstrapBlazor.MouseFollower/wwwroot/mouse-follower.bundle.css
Labels: enhancement

#192 refactor(Live2D): remove css isolation
  src/components/BootstrapBlazor.Live2DDisplay/BootstrapBlazor.Live2DDisplay.csproj
  src/components/BootstrapBlazor.Live2DDisplay/Components/Live2DDisplay/Live2DDisplay.razor.js
  src/components/BootstrapBlazor.Live2DDisplay/wwwroot/live2d.bundle.css
  src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor
  src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
Labels: enhancement

#194 refactor(CodeEditor): remove css isolation
  src/components/BootstrapBlazor.CodeEditor/BootstrapBlazor.CodeEditor.csproj
  src/components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.js
  src/components/BootstrapBlazor.CodeEditor/wwwroot/code-editor.bundle.css
Labels: enhancement

#196 feat(MeiliSearch): add SearchableColumns parameter
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
Labels: enhancement

#198 fix(OnScreenKeyboard): disable call dispose method
  src/components/BootstrapBlazor.OnScreenKeyboard/BootstrapBlazor.OnScreenKeyboard.csproj
  src/components/BootstrapBlazor.OnScreenKeyboard/OnScreenKeyboard.razor
Labels: enhancement

#200 feat(MeiliSearch): use variable in css
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#202 feat(MeiliSearch): add close function when click empty list
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#206 fix(DockView2): update ShowPin style
  src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
  src/components/BootstrapBlazor.DockView/wwwroot/css/dockview-bb.css
  src/components/BootstrapBlazor.DockView/wwwroot/js/dockview-group.js
Labels: bug

#210 fix(Html2Pdf): add disable web security config
  src/components/BootstrapBlazor.Html2Pdf/Services/DefaultPdfService.cs
Labels: bug

#212 feat(MeiliSearch): add ScrollIntoViewOptions parameter
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#214 feat(MeiliSearch): add EnterKeyText parameter
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
Labels: enhancement

#216 feat(MeiliSearch): add FooterTemplate parameter
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
Labels: enhancement

#218 feat(MeiliSearch): add SearchText parameter
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#220 refactor(MeiliSearch): remove SearchStatus parameter
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#222 feat(MeiliSearch): add ShowFooter parameter
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#224 feat(MeiliSearch): update style into BootstrapBlazor UI Lib
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
Labels: enhancement

#226 refactor(MeiliSearch): trigger link click event
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#228 feat(MeiliSearch): update max-height value
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#230 refactor(MeiliSearch): add search icon class
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#232 feat(MeiliSearch): dialog support ESC key
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.cs
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#234 feat(MindMap): redesign MindMap component
  src/components/BootstrapBlazor.MindMap/BootstrapBlazor.MindMap.csproj
  src/components/BootstrapBlazor.MindMap/MindMap.razor
  src/components/BootstrapBlazor.MindMap/MindMap.razor.cs
  src/components/BootstrapBlazor.MindMap/MindMap.razor.css
  src/components/BootstrapBlazor.MindMap/MindMap.razor.js
  src/components/BootstrapBlazor.MindMap/MindMapEnum.cs
  src/components/BootstrapBlazor.MindMap/MindMapOption.cs
  src/components/BootstrapBlazor.MindMap/wwwroot/mindmap.css
  src/components/BootstrapBlazor.MindMap/wwwroot/simpleMindMap.esm.min.js
Labels: enhancement
