Repository BootstrapBlazor/BootstrapBlazor.Extensions, pull requests merged in 2024-10, with the labels that each got.

#20 feat(SignaturePad): remove css isolation
  src/components/BootstrapBlazor.SignaturePad/BootstrapBlazor.SignaturePad.csproj
  src/components/BootstrapBlazor.SignaturePad/Directory.Build.props
  src/components/BootstrapBlazor.SignaturePad/SignaturePad.razor.cs
  src/components/BootstrapBlazor.SignaturePad/SignaturePad.razor.js
  src/components/BootstrapBlazor.SignaturePad/wwwroot/SignaturePad.css
Labels: enhancement

#22 feat(Topology): remove css isoloation
  src/components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
  src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
  src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.css
Labels: enhancement

#24 feat(TableExport): bump version 8.3.0
  src/components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
  src/components/BootstrapBlazor.TableExport/MiniExcelDataReaderBase.cs
Labels: enhancement

#26 feat(BaiduOrc): update dependence
  src/components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
Labels: enhancement

#28 refactor(OCR): bump version 8.1.0
  src/components/BootstrapBlazor.OCR/AiForm.razor.cs
  src/components/BootstrapBlazor.OCR/AiFormDocumentEmnu.cs
  src/components/BootstrapBlazor.OCR/AzureOpenAI.razor.cs
  src/components/BootstrapBlazor.OCR/AzureSTS.razor.cs
  src/components/BootstrapBlazor.OCR/BootstrapBlazor.OCR.csproj
  src/components/BootstrapBlazor.OCR/Directory.Build.props
  src/components/BootstrapBlazor.OCR/EnumAzureOpenAIModel.cs
  src/components/BootstrapBlazor.OCR/EnumVoiceName.cs
  src/components/BootstrapBlazor.OCR/OCR.razor.cs
  src/components/BootstrapBlazor.OCR/PlayAudio.razor.cs
  src/components/BootstrapBlazor.OCR/Services/AiFormService.cs
  src/components/BootstrapBlazor.OCR/Services/AiFormServiceCollectionExtensions.cs
  src/components/BootstrapBlazor.OCR/Services/BaseService.cs
  src/components/BootstrapBlazor.OCR/Services/OcrService.cs
  src/components/BootstrapBlazor.OCR/Services/OcrServiceAdv.cs
  src/components/BootstrapBlazor.OCR/Services/OcrServiceCollectionExtensions.cs
  src/components/BootstrapBlazor.OCR/Services/OpenAIClientService.cs
  src/components/BootstrapBlazor.OCR/Services/StsService.cs
  src/components/BootstrapBlazor.OCR/Services/TranslateService.cs
  src/components/BootstrapBlazor.OCR/Translate.razor.cs
  src/components/BootstrapBlazor.OCR/Utils/Utils.cs
Labels: enhancement

#30 chore(FileViewer): bump version 8.1.1
  src/components/BootstrapBlazor.FileViewer/BootstrapBlazor.FileViewer.csproj
Labels: chore

#32 feat(Html2Pdf): bump version 8.2.1
  src/components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj
Labels: enhancement

#34 chore(AntDesignIcon): bump version 8.1.0
  src/Directory.Build.props
  src/Frameworks.props
  src/components/BootstrapBlazor.AntDesignIcon/BootstrapBlazor.AntDesignIcon.csproj
Labels: chore

#36 chore(CodeEditor): bump version 8.1.0
  src/components/BootstrapBlazor.CodeEditor/BootstrapBlazor.CodeEditor.csproj
  src/components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.js
Labels: chore

#38 chore(CodeEditor): bump version 8.1.1
  src/components/BootstrapBlazor.CodeEditor/BootstrapBlazor.CodeEditor.csproj
  src/components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.js
Labels: chore

#40 chore(Dock): bump version 8.2.0
  src/components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
Labels: chore

#42 chore(AzureOpenAI): bump version 8.1.0
  src/components/BootstrapBlazor.AzureOpenAI/BootstrapBlazor.AzureOpenAI.csproj
  src/components/BootstrapBlazor.AzureOpenAI/Services/AzureOpenAIChatMessage.cs
  src/components/BootstrapBlazor.AzureOpenAI/Services/AzureOpenAIService.cs
Labels: enhancement

#44 chore(AzureSpeech): bump version 8.1.0
  src/components/BootstrapBlazor.AzureSpeech/BootstrapBlazor.AzureSpeech.csproj
Labels: chore

#46 chore(AzureTranslator): bump version 8.1.1
  src/components/BootstrapBlazor.AzureTranslator/BootstrapBlazor.AzureTranslator.csproj
Labels: chore

#48 chore(BaiduOcr): bump version 8.1.2
  src/components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
Labels: chore

#50 chore(SummerNote): bump version 8.1.0
  src/components/BootstrapBlazor.BaiduSpeech/BootstrapBlazor.BaiduSpeech.csproj
  src/components/BootstrapBlazor.BaiduSpeech/Services/BaiduRecognizerProvider.cs
  src/components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
Labels: chore

#52 chore(Holiday): bump version 8.1.0
  BootstrapBlazor.Extensions.sln
  src/components/BootstrapBlazor.Holiday/BootstrapBlazor.Holiday.csproj
  src/components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
  test/Directory.Build.props
  test/UnitTestEditor/BootstrapBlazorTestBase.cs
  test/UnitTestEditor/EditorTest.cs
  test/UnitTestEditor/UnitTestEditor.csproj
  test/UnitTestHoliday/UnitTest1.cs
  test/UnitTestHoliday/UnitTestHoliday.csproj
Labels: chore

#54 chore(BaiduSpeech): bump version 8.1.1
  src/components/BootstrapBlazor.BaiduSpeech/Services/BaiduRecognizerProvider.cs
  test/Directory.Build.props
Labels: chore

#56 feat(BarcodeGenerator): redesign BarcodeGenerator component
  .github/workflows/build.yml
  src/components/BootstrapBlazor.BarcodeGenerator/BarCodeGenerator.razor
  src/components/BootstrapBlazor.BarcodeGenerator/BarCodeGenerator.razor.cs
  src/components/BootstrapBlazor.BarcodeGenerator/BarCodeGenerator.razor.js
  src/components/BootstrapBlazor.BarcodeGenerator/BarcodeGenerator.razor
  src/components/BootstrapBlazor.BarcodeGenerator/BarcodeGenerator.razor.cs
  src/components/BootstrapBlazor.BarcodeGenerator/BarcodeGenerator.razor.js
  src/components/BootstrapBlazor.BarcodeGenerator/BarcodeGeneratorOption.cs
  src/components/BootstrapBlazor.BarcodeGenerator/BarcodeGeneratorOptionsExtensions.cs
  src/components/BootstrapBlazor.BarcodeGenerator/BootstrapBlazor.BarcodeGenerator.csproj
  src/components/BootstrapBlazor.BarcodeGenerator/EnumBarcodeFormat.cs
  src/components/BootstrapBlazor.BarcodeGenerator/EnumBarcodeTextAlign.cs
  src/components/BootstrapBlazor.BarcodeGenerator/EnumBarcodeTextFont.cs
  src/components/BootstrapBlazor.BarcodeGenerator/EnumBarcodeTextFontOption.cs
  src/components/BootstrapBlazor.BarcodeGenerator/EnumBarcodeTextPosition.cs
  src/components/BootstrapBlazor.BarcodeGenerator/EnumBarcodeType.cs
  src/components/BootstrapBlazor.BarcodeGenerator/wwwroot/JsBarcode.all.min.js
  src/components/BootstrapBlazor.Core/readme.md
Labels: enhancement

#60 chore(BootstrapIcon): bump version 8.1.0
  src/components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj
Labels: chore

#62 chore(ChartJs): bump version 8.3.0
  src/components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
  src/components/BootstrapBlazor.Chart/Components/Chart/Chart.razor.js
  src/components/BootstrapBlazor.Chart/Directory.Build.targets
  src/components/BootstrapBlazor.Chart/wwwroot/js/chart.js
Labels: chore

#58 chore(FileViewer): bump version 8.2.0
  src/components/BootstrapBlazor.FileViewer/BootstrapBlazor.FileViewer.csproj
Labels: chore

#66 chore(Release): add release yaml
  .github/workflows/release.yml
  src/Directory.Build.props
  src/components/BootstrapBlazor.AntDesignIcon/BootstrapBlazor.AntDesignIcon.csproj
  src/components/BootstrapBlazor.AzureOpenAI/BootstrapBlazor.AzureOpenAI.csproj
  src/components/BootstrapBlazor.AzureSpeech/BootstrapBlazor.AzureSpeech.csproj
  src/components/BootstrapBlazor.AzureTranslator/BootstrapBlazor.AzureTranslator.csproj
  src/components/BootstrapBlazor.BaiduMap/BootstrapBlazor.BaiduMap.csproj
  src/components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
  src/components/BootstrapBlazor.BaiduSpeech/BootstrapBlazor.BaiduSpeech.csproj
  src/components/BootstrapBlazor.BarCode/BootstrapBlazor.BarCode.csproj
  src/components/BootstrapBlazor.BarcodeGenerator/BootstrapBlazor.BarcodeGenerator.csproj
  src/components/BootstrapBlazor.Bluetooth/Directory.Build.props
  src/components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj
  src/components/BootstrapBlazor.Chart/BootstrapBlazor.Chart.csproj
  src/components/BootstrapBlazor.CherryMarkdown/BootstrapBlazor.CherryMarkdown.csproj
  src/components/BootstrapBlazor.CodeEditor/BootstrapBlazor.CodeEditor.csproj
  src/components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
  src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
  src/components/BootstrapBlazor.DriverJs/BootstrapBlazor.DriverJs.csproj
  src/components/BootstrapBlazor.ElementIcon/BootstrapBlazor.ElementIcon.csproj
  src/components/BootstrapBlazor.FileViewer/BootstrapBlazor.FileViewer.csproj
  src/components/BootstrapBlazor.FloatingUI/BootstrapBlazor.FloatingUI.csproj
  src/components/BootstrapBlazor.FontAwesome/BootstrapBlazor.FontAwesome.csproj
  src/components/BootstrapBlazor.Gantt/BootstrapBlazor.Gantt.csproj
  src/components/BootstrapBlazor.Holiday/BootstrapBlazor.Holiday.csproj
  src/components/BootstrapBlazor.Html2Pdf.iText/BootstrapBlazor.Html2Pdf.iText.csproj
  src/components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj
  src/components/BootstrapBlazor.IconPark/BootstrapBlazor.IconPark.csproj
  src/components/BootstrapBlazor.ImageCropper/BootstrapBlazor.ImageCropper.csproj
  src/components/BootstrapBlazor.Live2DDisplay/BootstrapBlazor.Live2DDisplay.csproj
  src/components/BootstrapBlazor.Markdown/BootstrapBlazor.Markdown.csproj
  src/components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
  src/components/BootstrapBlazor.MaterialDesign/BootstrapBlazor.MaterialDesign.csproj
  src/components/BootstrapBlazor.MouseFollower/BootstrapBlazor.MouseFollower.csproj
  src/components/BootstrapBlazor.OCR/BootstrapBlazor.OCR.csproj
  src/components/BootstrapBlazor.OnScreenKeyboard/BootstrapBlazor.OnScreenKeyboard.csproj
  src/components/BootstrapBlazor.Player/BootstrapBlazor.Player.csproj
  src/components/BootstrapBlazor.SignaturePad/BootstrapBlazor.SignaturePad.csproj
  src/components/BootstrapBlazor.Sortable/BootstrapBlazor.Sortable.csproj
  src/components/BootstrapBlazor.Splitting/BootstrapBlazor.Splitting.csproj
  src/components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
  src/components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
  src/components/BootstrapBlazor.TagHelper/BootstrapBlazor.TagHelper.csproj
  src/components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
  src/components/BootstrapBlazor.WinBox/BootstrapBlazor.WinBox.csproj
Labels: chore

#68 chore(middleware): update project path
  BootstrapBlazor.Extensions.sln
  src/Middleware/BootstrapBlazor.Middleware/logo.png
  src/middleware/BootstrapBlazor.Middleware/BootstrapBlazor.Middleware.csproj
  src/middleware/BootstrapBlazor.Middleware/BootstrapBlazorApplicationBuilderExtensions.cs
  src/middleware/BootstrapBlazor.Middleware/InternalIPAddressExtensions.cs
Labels: chore

#70 chore(Markdown): bump version 8.2.1
  src/components/BootstrapBlazor.Markdown/BootstrapBlazor.Markdown.csproj
  src/components/BootstrapBlazor.Markdown/bundleconfig.json
  src/components/BootstrapBlazor.Markdown/wwwroot/css/bootstrap.blazor.markdown.min.css
  src/components/BootstrapBlazor.Markdown/wwwroot/css/markdown.css
Labels: chore

#72 chore(SqlSugar): bump version 8.3.1
  src/extensions/BootstrapBlazor.DataAccess.SqlSugar/BootstrapBlazor.DataAccess.SqlSugar.csproj
Labels: chore

#74 chore(PetaPoco): bump version 8.3.1
  src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
Labels: chore

#76 chore(EFCore): remove net5 support
  src/extensions/BootstrapBlazor.DataAccess.EntityFrameworkCore/BootstrapBlazor.DataAccess.EntityFrameworkCore.csproj
Labels: chore

#78 test(Editor): add bUnit namespace
  test/UnitTestEditor/BootstrapBlazorTestBase.cs
  test/UnitTestEditor/EditorTest.cs
Labels: chore

#80 fix(PetaPoco): missing where keyword
  src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
  src/extensions/BootstrapBlazor.DataAccess.PetaPoco/DatabaseExtensions.cs
Labels: bug

#82 feat(PetaPoco): add AddPetaPoco extension method
  src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
  src/extensions/BootstrapBlazor.DataAccess.PetaPoco/PetaPocoServiceCollectionExtensions.cs
Labels: enhancement

#84 chore(CI&CD): update yml config
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/docker.yml
  .github/workflows/pack.yml
  .github/workflows/publish.yml
Labels: chore

#86 feat(PetaPoco): add IServiceProvider parameter
  src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
  src/extensions/BootstrapBlazor.DataAccess.PetaPoco/PetaPocoServiceCollectionExtensions.cs
Labels: enhancement

#88 chore(Generator): bump version 8.4.0
  src/components/BootstrapBlazor.BarcodeGenerator/BarcodeGeneratorOption.cs
  src/components/BootstrapBlazor.BarcodeGenerator/BootstrapBlazor.BarcodeGenerator.csproj
Labels: enhancement

#90 chore(ImageCropper): bump version 8.3.0
  src/components/BootstrapBlazor.ImageCropper/BootstrapBlazor.ImageCropper.csproj
  src/components/BootstrapBlazor.ImageCropper/ImageCropperOption.cs
Labels: chore

#92 chore(Player): bump version 8.3.0
  src/components/BootstrapBlazor.Player/BootstrapBlazor.Player.csproj
  src/components/BootstrapBlazor.Player/PlayerMode.cs
  src/components/BootstrapBlazor.Player/PlayerSource.cs
Labels: chore

#94 chore(DockView): bump version 8.4.0
  src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
  src/components/BootstrapBlazor.DockView/Components/DockViewContentType.cs
  src/components/BootstrapBlazor.DockView/Components/DockViewRenderMode.cs
Labels: chore

#96 chore(HtmlToPdf): add HtmlToPdf.Select lib
  BootstrapBlazor.Extensions.sln
  src/components/BootstrapBlazor.Html2Pdf.Select/BootstrapBlazor.Html2Pdf.Select.csproj
  src/components/BootstrapBlazor.Html2Pdf.Select/Extensions/ServiceCollectionExtensions.cs
  src/components/BootstrapBlazor.Html2Pdf.Select/Services/DefaultPdfService.cs
Labels: chore

#97 feat(Topology): add IsDsiableAnchor parameter
  src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
  src/components/BootstrapBlazor.Topology/wwwroot/fillLines.js
Labels: enhancement

#100 feat(Topology): add disableAnchor method
  src/components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
  src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
  src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
  src/components/BootstrapBlazor.Topology/wwwroot/fillLines.js
Labels: enhancement
