Repository BootstrapBlazor/BootstrapBlazor.Extensions, pull requests merged in 2025-01, with the labels that each got.

#236 feat(BootstrapIcon): use FrozenDictionary improve performance
  src/components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj
  src/components/BootstrapBlazor.BootstrapIcon.Extensions/DefaultIcon.cs
  src/components/BootstrapBlazor.BootstrapIcon.Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#238 feat(MateriaDesignIcon): use FrozenDictionary improve performance
  src/components/BootstrapBlazor.MaterialDesign.Extensions/BootstrapBlazor.MaterialDesign.Extensions.csproj
  src/components/BootstrapBlazor.MaterialDesign.Extensions/DefaultIcon.cs
  src/components/BootstrapBlazor.MaterialDesign.Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#240 test(Icon): add Icon unit test
  BootstrapBlazor.Extensions.sln
  test/UniTestSvgIcon/UniTestSvgIcon.csproj
  test/UniTestSvgIcon/UnitTest.cs
  test/UniTestSvgIcon/download.zip
  test/UniTestSvgIcon/element.svg
  test/UniTestSvgIcon/element.zip
  test/UniTestSvgIcon/filled.svg
  test/UniTestSvgIcon/filled.zip
  test/UniTestSvgIcon/icon-park.svg
  test/UniTestSvgIcon/outlined.svg
  test/UniTestSvgIcon/outlined.zip
  test/UniTestSvgIcon/twotone.svg
  test/UniTestSvgIcon/twotone.zip
Labels: test

#242 feat(MindMap): add callback extensions
  src/components/BootstrapBlazor.MindMap/BootstrapBlazor.MindMap.csproj
  src/components/BootstrapBlazor.MindMap/MindMap.razor.cs
  src/components/BootstrapBlazor.MindMap/MindMap.razor.js
  src/components/BootstrapBlazor.MindMap/MindMapNode.cs
  src/components/BootstrapBlazor.MindMap/MindMapOption.cs
  src/components/BootstrapBlazor.MindMap/wwwroot/mindmap.css
  src/components/BootstrapBlazor.MindMap/wwwroot/themes.esm.min.js
Labels: enhancement

#244 feat(MeiliSearch): update search model
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/MeiliSearchBox.razor.js
Labels: enhancement

#246 refactor(MindMap): fix throw exception issue
  src/components/BootstrapBlazor.MindMap/BootstrapBlazor.MindMap.csproj
  src/components/BootstrapBlazor.MindMap/MindMap.razor.cs
  src/components/BootstrapBlazor.MindMap/MindMap.razor.js
Labels: enhancement

#247 chore(Sponsor): add Sponsor button
  .github/FUNDING.yml
Labels: chore

#250 feat(TableExport): support lookup GetItemsAsync extension method
  src/components/BootstrapBlazor.TableExport/BootstrapBlazor.TableExport.csproj
  src/components/BootstrapBlazor.TableExport/Extensions/ITableColumnExtensions.cs
  src/components/BootstrapBlazor.TableExport/Services/DefaultTableExport.cs
  src/components/BootstrapBlazor.TableExport/Services/ExportDataReader.cs
Labels: enhancement

#252 feat(Markdown): use Id instead of ElementReference
  src/components/BootstrapBlazor.Markdown/BootstrapBlazor.Markdown.csproj
  src/components/BootstrapBlazor.Markdown/Components/Markdown/Markdown.razor
  src/components/BootstrapBlazor.Markdown/Components/Markdown/Markdown.razor.cs
  src/components/BootstrapBlazor.Markdown/Components/Markdown/Markdown.razor.js
Labels: enhancement

#258 feat(RDKit): add update support
  src/components/BootstrapBlazor.RDKit/RDKit.razor.cs
  src/components/BootstrapBlazor.RDKit/RDKit.razor.js
Labels: enhancement

#260 feat(RDKit): add size parameter
  src/components/BootstrapBlazor.RDKit/BootstrapBlazor.RDKit.csproj
  src/components/BootstrapBlazor.RDKit/RDKit.razor.cs
  src/components/BootstrapBlazor.RDKit/RDKit.razor.js
Labels: enhancement

#262 feat(SmilesDrawer): add SmilesDrawer component (#261)
  BootstrapBlazor.Extensions.sln
  src/components/BootstrapBlazor.SmilesDrawer/BootstrapBlazor.SmilesDrawer.csproj
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawer.razor
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawer.razor.cs
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawer.razor.css
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawer.razor.js
  src/components/BootstrapBlazor.SmilesDrawer/_Imports.razor
  src/components/BootstrapBlazor.SmilesDrawer/wwwroot/smiles-drawer.min.js
Labels: enhancement

#264 refactor(RDKit): update Value parameter to Smiles
  src/components/BootstrapBlazor.RDKit/BootstrapBlazor.RDKit.csproj
  src/components/BootstrapBlazor.RDKit/RDKit.razor.cs
Labels: enhancement

#265 feat(SmilesDrawer): add SmilesDrawer component
  BootstrapBlazor.Extensions.sln
  src/components/BootstrapBlazor.SmilesDrawer/BootstrapBlazor.SmilesDrawer.csproj
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawer.razor
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawer.razor.cs
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawer.razor.js
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawerOptions.cs
  src/components/BootstrapBlazor.SmilesDrawer/_Imports.razor
  src/components/BootstrapBlazor.SmilesDrawer/wwwroot/smiles-drawer.min.js
Labels: enhancement

#267 feat(SmilesDrawer): update SmilesDrawerOption
  src/components/BootstrapBlazor.SmilesDrawer/BootstrapBlazor.SmilesDrawer.csproj
  src/components/BootstrapBlazor.SmilesDrawer/SmilesDrawerOptions.cs
Labels: enhancement

#269 feat(SortableList): add Swap MultiDrag plugin
  src/components/BootstrapBlazor.Sortable/BootstrapBlazor.Sortable.csproj
  src/components/BootstrapBlazor.Sortable/Components/SortableList.razor.js
Labels: enhancement

#271 feat(Dockview): add overflow style
  src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
  src/components/BootstrapBlazor.DockView/wwwroot/css/dockview-bb.css
Labels: enhancement

#273 feat(Meilisearch): FooterLogo support responsive
  src/components/BootstrapBlazor.MeiliSearch/BootstrapBlazor.MeiliSearch.csproj
  src/components/BootstrapBlazor.MeiliSearch/wwwroot/meilisearch.css
Labels: enhancement

#279 feat(OctIcon): add OctIcon component
  BootstrapBlazor.Extensions.sln
  src/components/BootstrapBlazor.OctIcon/BootstrapBlazor.OctIcon.csproj
  src/components/BootstrapBlazor.OctIcon/OctIcon.razor
  src/components/BootstrapBlazor.OctIcon/OctIcon.razor.cs
  src/components/BootstrapBlazor.OctIcon/OctIcon.razor.css
  src/components/BootstrapBlazor.OctIcon/_Imports.razor
  src/components/BootstrapBlazor.OctIcon/wwwroot/octicon.svg
  test/UniTestSvgIcon/AntDesign/filled.svg
  test/UniTestSvgIcon/AntDesign/filled.zip
  test/UniTestSvgIcon/AntDesign/outlined.svg
  test/UniTestSvgIcon/AntDesign/outlined.zip
  test/UniTestSvgIcon/AntDesign/twotone.svg
  test/UniTestSvgIcon/AntDesign/twotone.zip
  test/UniTestSvgIcon/Element/element.zip
  test/UniTestSvgIcon/IconPark/download.zip
  test/UniTestSvgIcon/OctIcon/octicons.zip
  test/UniTestSvgIcon/UniTestSvgIcon.csproj
  test/UniTestSvgIcon/UnitTest.cs
Labels: enhancement
